### ISSUE TITLE
Crash when i print game.slug

### ISSUE THREAD

**Issue by Peter-Huang0623** [fedecalendino/nintendeals#7]
thanks for you job first, and i met this crash when i print game.slug, i don't know what caused this crash, hope you can fix it if it is a bug, and another problem is that some of the games' uuid is None when i call 
`list_switch_games()` method for example `Cyanide & Happiness – Freakpocalypse: Part 1`, this game doesn't have a nsuid.
```python
Traceback (most recent call last):
  File "nintendo_games.py", line 52, in <module>
    print(game.slug)
  File "/usr/local/lib/python3.8/site-packages/nintendeals/validate.py", line 173, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nintendeals/noe/info.py", line 215, in game_info
    return _scrap_switch(nsuid=nsuid)
  File "/usr/local/lib/python3.8/site-packages/nintendeals/noe/info.py", line 108, in _scrap_switch
    value, unit = rom_size.split(" ")
ValueError: too many values to unpack (expected 2)
```

**Comment by Peter-Huang0623** [comment]
and if i call `noa.list_switch_games()` it shows me this error:

```python
File "nintendo_games.py", line 49, in <module>
    for game in noa.list_switch_games():
  File "/usr/local/lib/python3.8/site-packages/nintendeals/noa/listing.py", line 128, in list_switch_games
    yield from _list_games(SwitchGame, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nintendeals/noa/listing.py", line 38, in _list_games
    game.players = int(re.sub(r"[^\d]*", "", data["numOfPlayers"]))
KeyError: 'numOfPlayers'
```

**Comment by fedecalendino** [comment]
@Peter-Huang0623 

* Regarding the first issue, games that haven't been unreleased yet usually don't have an nsuid assigned. That is why [here](https://github.com/fedecalendino/nintendeals/blob/master/nintendeals/noe/listing.py#L194) it says `nsuid: str (optional)` as can ensure that will be available or not.

* For the bug on `numOfPlayers`, I've just pushed the version [v1.6.1](https://github.com/fedecalendino/nintendeals/releases/tag/v1.6.1) that should fix this problem.

Thanks for opening the issue and letting me know about this :)
