### ISSUE TITLE
algoliasearch.exceptions.AlgoliaUnreachableHostException: Unreachable hosts

### ISSUE THREAD

**Issue by Peter-Huang0623** [fedecalendino/nintendeals#8]
this my code:
```python
from nintendeals import noa

def getUSGamesBrief():
    index = 1
    for game in noa.list_switch_games():
        print(index, "  ", game.title)
        index += 1

if __name__ == '__main__':
    getUSGamesBrief()
```
and it throw an exception when i run it:
```shell
/usr/local/bin/python3.9 /Users/mac/PycharmProjects/switch/venv/gamesUS.py
Traceback (most recent call last):
  File "/Users/mac/PycharmProjects/switch/venv/gamesUS.py", line 12, in <module>
    getUSGamesBrief()
  File "/Users/mac/PycharmProjects/switch/venv/gamesUS.py", line 7, in getUSGamesBrief
    for game in noa.list_switch_games():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nintendeals/noa/listing.py", line 52, in list_switch_games
    yield from list_games(Platforms.NINTENDO_SWITCH)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nintendeals/noa/listing.py", line 10, in list_games
    for data in algolia.search_by_platform(platform):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nintendeals/noa/api/algolia.py", line 63, in search_by_platform
    games = _search_index(query, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nintendeals/noa/api/algolia.py", line 34, in _search_index
    response = INDEX.search(query, request_options=options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/algoliasearch/search_index.py", line 284, in search
    return self._transporter.read(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/algoliasearch/http/transporter.py", line 47, in read
    return self.request(verb, hosts, path, data, request_options, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/algoliasearch/http/transporter.py", line 72, in request
    return self.retry(hosts, request, relative_url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/algoliasearch/http/transporter.py", line 94, in retry
    raise AlgoliaUnreachableHostException("Unreachable hosts")
algoliasearch.exceptions.AlgoliaUnreachableHostException: Unreachable hosts
```
Do you know why this happened？

**Comment by fedecalendino** [comment]
Hi @Peter-Huang0623 !

All tests for `nintendeals` seem to be working corretly: https://travis-ci.com/fedecalendino/nintendeals

So I'm guessing there is an issue with your connection.
I also tried your code snippet and its working as intended in my laptop.

Cheers, Fede.
